### ISSUE TITLE
Add User Input Validation

### ISSUE THREAD

**Issue by mlecoutre** [mlecoutre/nounou#4]
Display a message to the end-user to indicate that value are not correct

**Comment by mlecoutre** [comment]
We use jquery validation plugin

## Initialization

``` html
<script src="../js/jquery.validate-1.10.0.min.js"></script>
<script src="../js/additional-methods-1.10.0.min.js"></script>
```

In utilities.js loaded in each html pages,

``` javascript
 $(document).ready(function () {
        var language = window.navigator.userLanguage || window.navigator.language;
        language =  language.substring(0,2);
        if( language !=  "en"){
            console.log("Initialize validation message for "+language);
            $.getScript("../js/validation-locale/messages_"+language+".js");
        }
    });
```

In custom.css

``` css
label {
 width: 10em;
 }

label.error {
 position:left;
 width:80%;
 _position: absolute;
 text-shadow: 0 1px 0 rgba(0,0,0,.5);
 color: red; padding-left: .5em;
 vertical-align: top;
 background-color: #de4343;
 color:white;
 border-color: #c43d3d;
 border-radius:5px;
 -moz-border-radius:5px;
 }
```

## Usage

``` html
<form id="formUser" class="span4 registration">
   <label for="userEmail" data-i18n="registration.email" ></label><em>*</em>
   <input type="text" id="userEmail" placeholder="Email" class="required email">
</form>
```

For each form

``` javascript
$(document).ready(function () {
   $("#formUser").validate();
   //...
}
```
